// Generated by CoffeeScript 1.3.3
(function() {
  var settings;

  settings = new Store("settings", {});

  chrome.extension.onRequest.addListener(function(request, sender, sendResponse) {
    if (request.action === 'gpmeGetOptions') {
      return sendResponse(settings.toObject());
    }
  });

}).call(this);
